msupply-foundation/notify

- backend/graphql/notification_config/src/mutations/mod.rs
- backend/graphql/notification_config/src/mutations/update.rs
- backend/graphql/types/src/types/notification_config.rs
- backend/repository/migrations/2023-09-25-031335_recipient-notification-config/down.sql
- backend/repository/migrations/2023-09-25-031335_recipient-notification-config/up.sql
- backend/repository/src/db_diesel/notification_config.rs
- backend/repository/src/db_diesel/notification_config_row.rs
- backend/scheduled/src/process.rs
- backend/service/src/notification_config/create.rs
- backend/service/src/notification_config/mod.rs
- backend/service/src/notification_config/query.rs
- backend/service/src/notification_config/tests/query.rs
- backend/service/src/notification_config/update.rs
- frontend/packages/common/src/types/schema.ts
- frontend/packages/system/src/Notifications/Pages/ColdChain/parseConfig.ts
- frontend/packages/system/src/Notifications/Pages/Scheduled/parseConfig.ts
- frontend/packages/system/src/Notifications/api/operations.generated.ts
- frontend/packages/system/src/Notifications/api/operations.graphql
- frontend/packages/system/src/Notifications/types.ts
Closes #148
When processing a notification, we need to make sure that shared information (such as recipients) are made available to the backend. Treating these fields separately makes this easier to deal with.
Need to test that these are appropriately managed in both Cold chain and Scheduled notifications
Needed for #138
> Parse recipient_ids & lists into their own fields

- frontend/packages/system/src/Recipients/SqlRecipientLists/DetailEdit.tsx
- frontend/packages/system/src/Recipients/SqlRecipientLists/RecipientQueryEditor.tsx
Closes #142 
Adds a parameters button to top of sql recipients screen
Check that the parameters button shows at the top right hand side of the SQL recipients page.
Test that parameters panel can be re-opened if closed by the user.
> Added parameters link to sqlRecipients

- backend/graphql/lib.rs
- backend/graphql/playground.html
Adds a graphiql plugin for Logging into the app.
Adds the graphiql 'Explorer' plugin to make it easier to create a test out queries
(Part of RND Day Sep 2023)
Just played around a little bit.
I'm guessing we should probably some how build the login plugin from the common package or another?
The javascript code is horrenas I know, I couldn't figured out how to interactively build plugins from the graphql docs.
Ended up building it in JS based on description here...
https://github.com/graphql/graphiql/tree/main/packages/graphiql#plugins
I'm hoping someone better at react and js can make this production ready for open-mSupply.
> Adds a login button and explorer to graphql playground

- backend/repository/src/mock/mod.rs
- backend/repository/src/mock/sql_recipient_list.rs
- backend/scheduled/src/parse.rs
- backend/scheduled/src/process.rs
- backend/service/src/notification/enqueue.rs
- backend/service/src/notification_config/mod.rs
- backend/service/src/notification_config/query.rs
- backend/service/src/notification_config/recipients.rs
Closes #138 & #73 
This PR updates the `process_scheduled_notifications` function to send to the configured recipients.
This uses the newly create `get_notification_targets` function. 
This returns `NotificationTargets` based on any configured `recipients`, `recipients` or `sql_recipient_lists` configured
Configure a scheduled notification with different combinations for recipients, lists, and sql lists.
Check the right address & channels receive the test messages.
> 138 scheduled notifications should send to configured recipients

- build_windows.bat
- frontend/package.json
- frontend/packages/host/package.json
Closes #178
Passes the version number from jenkins build for windows into the webpack process so it can be shown in the UI.
Tested in Jenkins.
I tried various things, and tired to read about how to use [cross-env](https://www.npmjs.com/package/cross-env) but after wasting too much time went with the different build target approach.
Happy for someone else to make it more consistent!
> Add a build-windows command to yarn for jenkins to use

- backend/coldchain/src/process.rs
Closes #183
What it says on the box! Server local time is passed to the alert.
Only tested locally with my timezone so far.
To test, create a Cold Chain Alert and se what time is displayed
Do we need to do more here? Maybe display the actual timezone?
We could allow the user to specify a timezone for alerts?
Pass both UTC and Local time to the template incase people want to do something custom?
> 183 cold chain alert date time should be shown in server time

- backend/Cargo.lock
- backend/repository/src/mock/mod.rs
- backend/repository/src/mock/notification_query.rs
- backend/scheduled/Cargo.toml
- backend/scheduled/src/lib.rs
- backend/scheduled/src/parse.rs
- backend/scheduled/src/process.rs
- backend/scheduled/src/query.rs
- backend/service/src/notification/enqueue.rs
- backend/service/src/notification_config/recipients.rs
Closes #137 
Runs any configured queries and makes their data available in the rendering of the template.
Create a query which returns known data.
Create a notification config for a scheduled report
Add you query and update the body template to include data based on the reference name.
Could be something like this...
Query (last_10_temperature_logs):
```
SELECT s.name, tl.temperature, "time", "date"
FROM temperature_log tl
JOIN sensor s ON tl.sensor_id = s.id
ORDER BY date desc, time desc
LIMIT 10
```
Template (first record)
```
Sensor:  {{ last_10_temperature_logs.0.name }} Temperature {{ last_10_temperature_logs.0.temperature }}
```
Template all 10 records
```
{% for row in last_10_temperature_logs %}
{{row.name}}: {{row.temperature}}
{% endfor %}
```
Right now this is a nightmare to …
> 137 schedule notifications should load data from sql queries to render in the template

- .gitignore
- backend/Cargo.lock
- backend/README.md
- backend/configuration/base.yaml
- backend/configuration/example.yaml
- backend/repository/src/db_diesel/key_value_store.rs
- backend/server/Cargo.toml
- backend/server/src/lib.rs
- backend/server/src/logging.rs
- backend/server/src/main.rs
- backend/service/Cargo.toml
- backend/service/src/lib.rs
- backend/service/src/log_service.rs
- backend/service/src/service_provider.rs
- backend/service/src/settings.rs
- backend/service/src/test_utils.rs
Closes #173
This is a copy of the open-mSupply logging setup. 
It allows logging to the console and/or a log file.
By default it does both see `base.yaml`
Ideally should be tested on linux and windows.
Check that `max_file_count` and `max_file_size` are working (not actually 100% sure how they are managed, copied from open-mSupply so hoping that they work!)
Console logging won't show up on windows when running as a service, so we should setup the file based logging in this situation.
> Logging configuration from open-mSupply

- backend/graphql/notification_config/src/mutations/duplicate.rs
- backend/service/src/notification_config/duplicate.rs
- backend/service/src/notification_config/mod.rs
- backend/service/src/notification_config/query.rs
- backend/service/src/notification_config/tests/duplicate.rs
- backend/service/src/notification_config/tests/mod.rs
- frontend/packages/common/src/intl/locales/en/system.json
- frontend/packages/common/src/types/schema.ts
- frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
- frontend/packages/system/src/Notifications/Pages/ColdChain/CCNotificationEditPage.tsx
- frontend/packages/system/src/Notifications/Pages/ColdChain/parseConfig.ts
- frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditPage.tsx
- frontend/packages/system/src/Notifications/Pages/Scheduled/parseConfig.ts
Suggested PR changes
Uses the backend to duplicate configs, avoids need to have per plugin onDuplicate Function, adds a confirmation modal
> Duplicate configs in the backend

- frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditForm.tsx
- frontend/packages/system/src/Queries/NotificationQueries/DetailEdit.tsx
- frontend/packages/system/src/Queries/NotificationQueries/QueryEditor.tsx
Closes #243
Makes it possible to scroll the query text box and sql results in the queries page.
Example long query to use...
```
SELECT 
'a' as a,
'b' as b,
'c' as c,
'd' as d,
'e' as e,
'f' as f,
'g' as g,
'h' as h,
'i' as i,
'j' as j,
'k' as k,
'l' as l,
'm' as m,
'n' as n,
'o' as o,
'p' as p,
'q' as q,
'r' as r,
's' as s,
't' as t,
'u' as u,
'v' as v,
'w' as w,
'x' as x,
'y' as y,
'z' as z
FROM 
sensor
LIMIT 100
```
It's a bit unintuitive to resize the textarea to make space for query results, but making the whole app bar scrollable seemed difficult. I experimented with side by side query and results but that also feels a bit messy and has issues with query and result sizes.
Hopefully this hits the balance of usable but not too difficult to implement :)
> 243 no scroll bar shows in the queries main page

- backend/server/src/lib.rs
- backend/service/src/email/mod.rs
Closes #249
Not sure if this really fixes the error we saw, as we don't have good logging, and I haven't been able to re-create it.
The closest I've come to is manually panicing in a plugin which does kill the scheduled task processing without stopping the whole server, so I've changed the behaviour so it does exit the server in this situation.
I added a failing unwrap to scheduled task processing, this closed the join handle and caused the whole server to shutdown.
```
2023-11-17 17:21:35.674677000 [INFO] <actix_server::server:196>:Actix runtime found; starting in Actix runtime
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', scheduled/src/lib.rs:37:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-17 17:21:35.739012000 …
```
> 249 email error can stop processing

- frontend/packages/system/src/Notifications/Pages/ColdChain/parseConfig.ts
- frontend/packages/system/src/Notifications/Pages/Scheduled/parseConfig.ts
Closes #253
Turns out it wasn't a parsing/escaping issue... we weren't removing the old `configurationData` field from the config after it was parsed, so each time we saved the new `configurationData`, we included a child field of the previous `configurationData` - ah recursion!
- Create a new notification config, enable it, and click `Save and Run` a bunch of times
- View the log of the mutation input... configuration data should stay the same size :)
This doesn't fix the configuration data for all the configs that already have this nested stringified configuration data, but it does stop them growing any further. That should be fine right?
> 253 fix escaping in logs

- backend/Cargo.lock
- backend/service/src/notification/mod.rs
- backend/telegram/Cargo.toml
- backend/telegram/src/client/mod.rs
- backend/telegram/src/service/markdown.rs
- backend/telegram/src/service/mod.rs
- backend/templates/coldchain/recovered.md
- backend/templates/coldchain/temperature.md
Closes #245 
Closes #230 
**BEFORE**
**AFTER**
Some test cases are in the code, And have done a bit of testing with cold chain and other formats.
Would be good to do more testing though!
There's a few telegram things like `~strikethrough~` and `||spoiler||` that are in telegram but not in common markdown.
Would be nice to not escape those things so that they correctly display if someone is writing telegram style markdown.
I'm thinking this can be a wait to see/hear what issues people face before doing more though.
BTW: This is already a bit of a time sink, and we'll never get a perfect representation of everything in telegram :(
> 245 telegram markdown is not rendered correctly

- backend/service/src/notification/enqueue.rs
Part of #262
If there is an internal error during the processing of a notification event, create a phantom failed notification event with no recipient, so can see it in the notification event log.
Create and run a scheduled event with a broken body template. Go to the events page and see an empty failed event with the parsing error details.
- Seems a shame not to include the title if possible, but that may be the thing that failed to parse... probably possible but would cost more time
- The map_err is both a bit repetitive and I think not great that it has the side effect creating the event, but moving the adding of templates to tera to a separate `try_add_templates_to_tera` method involved a lot of passing things around e.g. the tera instance - but I'm not very confident in my Rust yet …
> 262 show parsing/processing errors in event log

- frontend/packages/common/src/intl/locales/en/system.json
- frontend/packages/common/src/localStorage/keys.ts
- frontend/packages/system/src/Queries/NotificationQueries/QueryEditor.tsx
- frontend/packages/system/src/Queries/NotificationQueries/SidePanel.tsx
- frontend/packages/system/src/Recipients/SqlRecipientLists/RecipientQueryEditor.tsx
- frontend/packages/system/src/Recipients/SqlRecipientLists/SidePanel.tsx
Closes #229
- Added the function to save parameters in the local storage in Queries and SQL Recipients
When all parameters(e.g. param1, param2) are already saved in the local storage, and user changes param1 and save it again, param1 should come from the user input, and param2 should come from the local storage. 
But I could not manage it...
or
> #229 Remember Parameters

- frontend/packages/common/src/ui/layout/tables/types.ts
- frontend/packages/system/src/NotificationEvents/ListView/ListView.tsx
- frontend/packages/system/src/Notifications/ListView/ListView.tsx
Closes #260
Fixes missing pagination controls on Notifications and Events pages. It wasn't rendering as the total count wasn't being provided.
Updated the DataTable pagination input type to require `total`.
Pagination controls should be available on both pages (and all others)
> 260 pagination fix

- frontend/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
[As found in Universal Codes](https://github.com/msupply-foundation/unified-codes/pull/434#discussion_r1423310098)
There was some kind of race condition going on with the clear search `X` button. Sometimes the `onClick` would fire and clear the search, but sometimes the focus would shift away from the input first, so the search field would shrink without clearing.
This PR updates the clear logic to run on `onMouseDown`, which fires before the focus change, so the search will reliably clear!
Type in a search field and clear it lots of times 😅
> fix search bar clearance race condition

- backend/coldchain/src/latest_temperature.rs
- backend/repository/src/tests.rs
Closes #283
Ignores datapoints with temperature over 55 degrees, these are very likely to be not correct in cold chain installations.
not much testing done yet, we'll leave this to QA to verify.
> 283 mask outlier temperature spikes

- backend/scheduled/src/process.rs
- backend/scheduled/src/query.rs
Closes #286
Adds some additional logging and timing information to scheduled reports
Also skips any parameter sets with no reciepients (saving time if there's a lot of parameter sets with not recipients)
```
2024-02-12 12:27:44.703764000 [INFO] <scheduled::process:145>:Processing parameter set: {"project":"MOVEX","province":"NOT A PROVINCE"}
2024-02-12 12:27:44.714748000 [INFO] <scheduled::process:159>:No notification targets, skipping
2024-02-12 12:27:44.714942000 [INFO] <scheduled::process:51>:Successfully created notification events
```
A little bit of testing locally, there's not new tests cases added.
There's a slight change in behaviour here, as it used to be that sql recipients could use parameters from SQL Queries run. I think this logic is easier and clearer though.
_No user …
> Improve logging, and skip parameter sets with not recipients

- frontend/packages/system/src/NotificationEvents/DetailView/DetailView.tsx
- frontend/packages/system/src/NotificationEvents/ListView/ListView.tsx
Closes #266
Fix console errors that occur when displaying certain tooltips.
Loading up the events view and checking the console, you should no longer see tooltip errors.
These errors were also causing the tooltips to fail to display, so you should now be able to hover over date entries and actually see the tooltip
> 266 - Fixup tool tip errors

- backend/repository/src/db_diesel/notification_event_row.rs
- backend/service/src/notification/mod.rs
Closes #92
Rather than retrying errored notifications immediately, wait 15/30/60 minutes (double each retry)
Tested by intentionally erroring a notification (easy to do, just don't run an instance of mailhog and all notifs will error), tested with a reduced `RETRY_DELAY_MINUTES` of `1`
> Actually use "retry_at" field in notifications

- backend/repository/src/db_diesel/notification_event_row.rs
- backend/repository/src/mock/notification_query.rs
- backend/scheduled/src/parse.rs
- backend/scheduled/src/process.rs
- backend/scheduled/src/query.rs
- backend/service/src/notification/enqueue.rs
- frontend/package.json
- frontend/packages/common/src/intl/locales/en/common.json
- frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditForm.tsx
- frontend/packages/system/src/Notifications/Pages/Scheduled/parseConfig.ts
- frontend/packages/system/src/Notifications/components/SqlQuerySelector.tsx
- frontend/packages/system/src/Notifications/types.ts
Closes #300
Makes it possible to mark a query as required.
If a query is required scheduled notifications won't run when there's no data returned for that query.
I think there's some kind of bug where the notification config gets over-written when clicking required.
I saw it happen twice but can't replicate now.
or
> 300 required querys
