msupply-foundation/notify

README.md

Linux builds require a postgres library `libpq` adding this to the Project README.md

Add instructions for installing libpq on ubuntu linux

---

frontend/packages/common/src/intl/locales/en/system.json
frontend/packages/common/src/ui/icons/Telegram.tsx
frontend/packages/common/src/ui/icons/index.ts
frontend/packages/system/src/Recipients/Recipients/RecipientEditModal/RecipientEditForm.tsx
frontend/packages/system/src/Recipients/api/hooks/useTelegramTestMessage.ts
frontend/packages/system/src/Recipients/api/operations.generated.ts
frontend/packages/system/src/Recipients/api/operations.graphql

Closes #53
Quick local test
Thinking this is a good thing for people to play with when playing with the bot...

Send test message to telegram recipients

---

backend/datasource/Cargo.toml
backend/repository/src/db_diesel/mod.rs
backend/telegram/Cargo.toml

Closes #86
Fixes lint warning with later versions of rust

Fix private item shadows public glob re-export lint

---

backend/graphql/core/src/standard_graphql_error.rs
backend/graphql/telegram/src/mutations/mod.rs

Closes #
Uses `from_string` for `standard_graphql_error`

Example of mapr vs match

---

backend/service/src/notification/enqueue.rs

Closes #94
Creates an errored notification if a notification title template can't be rendered

94 handle title template error

---

backend/coldchain/Cargo.toml
backend/coldchain/src/lib.rs
backend/repository/migrations/2023-08-17-042604_create_notification_event/up.sql
backend/repository/migrations/2023-09-10-231506_notification_attempts/down.sql
backend/repository/migrations/2023-09-10-231506_notification_attempts/up.sql
backend/repository/src/db_diesel/notification_event_row.rs
backend/service/src/email/mod.rs
backend/service/src/email/send.rs
backend/service/src/notification/enqueue.rs
backend/service/src/notification/mod.rs
backend/service/src/test_utils.rs
backend/telegram/src/client/mod.rs
backend/templates/coldchain/telegram/temperature.html
backend/templates/coldchain/telegram/temperature_title.html

Closes #91
- Refactors email queue (Used for sending password reset etc)
- Enabled email sending for notifications
- Test case in coldchain which can be run with 
`cargo test --features email-tests,telegram-tests  --package coldchain --lib -- tests::test_send_high_temperature_alert --exact --nocapture`
You'll need to run `mailhog` and setup your telegram env 
I plan to do exponential back off at some stage.
https://github.com/openmsupply/notify/issues/92

Email Sending

---

backend/graphql/core/Cargo.toml
build_deb_package.sh
frontend/packages/common/src/ui/components/portals/DetailPanel/DetailPanel.test.tsx
frontend/packages/config/src/config.ts
frontend/packages/config/src/index.ts
frontend/packages/host/src/Host.tsx
frontend/packages/host/webpack.config.js

Closes #121 
Make the bugsnag key optional.
Changes key so notify alerts aren't mixed with health supply hub

Bugsnag API Key

---

frontend/packages/common/src/ui/components/index.ts
frontend/packages/system/src/Notifications/ListView/ListView.tsx
frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationAppBar.tsx
frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
frontend/packages/system/src/Notifications/Pages/CreateConfigKindModal.tsx

suggested changes

---

frontend/packages/host/src/Site.tsx

Navigates to Notifications page, if you haven't specified a page during login

Default the navigation to /notifications

---

frontend/packages/system/src/Notifications/Modals/Scheduled/ScheduledNotificationEditModal.tsx
frontend/packages/system/src/Notifications/Modals/Scheduled/parseConfig.ts

100 poc scheduled report configurations(simplify notification config parsing)

---

frontend/packages/system/src/Notifications/Pages/ColdChain/CCNotificationEditForm.tsx

Closes #159 
Fixes a labeling issue (low temp)
Adds better mock locations

Better Mock Locations, fix label for low temp

---

backend/repository/src/db_diesel/notification_config_row.rs
backend/service/src/notification_config/tests/query.rs

Closes #166 
- Added to check the status in `find_all_due_by_kind`
- Added the test case for checking 'Disabled' is not collected by `find_all_due_by_kind` function
or

#166 Enable/Disable alerts for Scheduled Notifications

---

backend/Cargo.lock
backend/Cargo.toml
backend/server/src/lib.rs
backend/server/src/main.rs
backend/windows/Cargo.toml
backend/windows/src/windows.rs

Closes #161 
Allows building the server as a windows service.
Register the service with a command like this:
`sc create Notify binpath="C:\Program Files\notify\notify_service.exe"`
Pretty much a copy and past from open-msupply, but a few false starts with small differences like logging config,

161 windows service

---

backend/service/src/notification/enqueue.rs

Closes #115
Added the code to dedup recipients by to_address.
Do we need to check the notification type (Telegram/Email) as well? 
or

#115 Dedup Notification Recipients

---

backend/graphql/notification_config/src/mutations/mod.rs
backend/graphql/notification_config/src/mutations/update.rs
backend/graphql/types/src/types/notification_config.rs
backend/repository/migrations/2023-09-25-031335_recipient-notification-config/down.sql
backend/repository/migrations/2023-09-25-031335_recipient-notification-config/up.sql
backend/repository/src/db_diesel/notification_config.rs
backend/repository/src/db_diesel/notification_config_row.rs
backend/scheduled/src/process.rs
backend/service/src/notification_config/create.rs
backend/service/src/notification_config/mod.rs
backend/service/src/notification_config/query.rs
backend/service/src/notification_config/tests/query.rs
backend/service/src/notification_config/update.rs
frontend/packages/common/src/types/schema.ts
frontend/packages/system/src/Notifications/Pages/ColdChain/parseConfig.ts
frontend/packages/system/src/Notifications/Pages/Scheduled/parseConfig.ts
frontend/packages/system/src/Notifications/api/operations.generated.ts
frontend/packages/system/src/Notifications/api/operations.graphql
frontend/packages/system/src/Notifications/types.ts

Closes #148 
Move recipient configs into their own fields in the database, making it easier to shared backend code to extract the recipients.
Needed for #138

Parse recipient_ids & lists into their own fields

---

backend/graphql/telegram/src/types.rs
backend/service/src/recipient/telegram.rs
backend/telegram/src/client/mod.rs
backend/telegram/src/lib.rs
backend/telegram/src/service/processor.rs
backend/telegram/src/service/responder.rs

Closes #158 
Closes #157 
Would be good to test it with a scheduled notification, as well as the test message in the reciepients screen.
Also try adding a removing from groups and channels to make sure there are no errors with these things

Handle telegram channels & respond to channel joins

---

backend/graphql/user_account/src/mutations/create.rs
backend/graphql/user_account/src/mutations/invite_user.rs
backend/graphql/user_account/src/mutations/update.rs
backend/service/src/notification_config/mod.rs
backend/service/src/recipient/mod.rs
backend/service/src/recipient_list/mod.rs
backend/service/src/sql_recipient_list/mod.rs
backend/service/src/user_account/mod.rs
backend/service/src/user_account/passwords.rs

Closes #190 
Removes some PartialEq implementations, that weren't needed and were causing bad copy and pasting behaviour :)
No testing is required, rust compiles!

Remove manual PartialEq implementations

---

frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditForm.tsx
frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditPage.tsx
frontend/packages/system/src/Notifications/components/SqlQuerySelector.tsx

some ui suggestions

---

frontend/packages/common/src/ui/components/popover/InfoTooltipIcon/InfoTooltipIcon.tsx
frontend/packages/system/src/Notifications/Pages/ColdChain/CCNotificationEditForm.tsx

update to use info icon component

---

docs/decisions/002-parameters.md

Closes #208
KDD about how to manage parameters in Notify
N/A
This is a KDD, so the document be updated to explain any questions...

KDD-002 Parameters Draft

---

backend/windows/src/windows.rs

Add logging config to windows service

---

backend/templates/coldchain/no_data.html
backend/templates/coldchain/recovered.html

Closes #225
It would be good to check all the different statuses to make sure they display well,
E.g. NoData, High, Low, and OK

Add current temperature to recovery message

---

frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditForm.tsx

Closes #237
Quick hack to show all the queries
Added another issue for a longer term fix here:
https://github.com/msupply-foundation/notify/issues/238
Create more than 20 queries, check if you can select them or not!

Allow up to 1000 queries to be returned for selection

---

backend/Cargo.lock
backend/graphql/notification_config/Cargo.toml
backend/graphql/notification_config/src/mutations/update.rs
backend/scheduled/src/process.rs
backend/service/src/notification_config/tests/duplicate.rs
backend/service/src/notification_config/update.rs
frontend/packages/common/src/intl/locales/en/common.json
frontend/packages/common/src/types/schema.ts
frontend/packages/common/src/ui/icons/Run.tsx
frontend/packages/common/src/ui/icons/index.ts
frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
frontend/packages/system/src/Notifications/Pages/ColdChain/CCNotificationEditPage.tsx
frontend/packages/system/src/Notifications/Pages/ColdChain/parseConfig.ts
frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditPage.tsx
frontend/packages/system/src/Notifications/Pages/Scheduled/parseConfig.ts
frontend/packages/system/src/Notifications/types.ts

Closes #246 
Adds a run now button, which schedules the notification to run immediately

246 add a run now button for notifications

---

backend/graphql/notification_config/src/types/inputs.rs
backend/repository/src/db_diesel/notification_config.rs
frontend/packages/common/src/types/schema.ts
frontend/packages/system/src/Notifications/ListView/ListView.tsx

Closes `nada`
Found it was useful to be able to sort notification config for ones that are enabled, especially when testing and you need to check lot of things
Check that the sorting works, and doesn't adversly affect anything else.

Allow sorting for enabled configs

---

frontend/packages/common/src/utils/tera/TeraUtils.test.ts
frontend/packages/common/src/utils/tera/TeraUtils.ts

Closes #289
Don't return duplicates when parsing Tera parameters
I've added an additional unit test for this case
or

Don't repeat duplicate query parameters

---

backend/scheduled/src/parse.rs

Closes #295
- Calculate monthly schedule all at once to prevent truncation
- Add a unit test for monthly configs running through short months

295 Fixup date truncation

---

frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditForm.tsx
frontend/packages/system/src/Notifications/components/SqlQuerySelector.tsx

state fresh
